In [1]:
import pandas as pd

In [2]:
election_data = pd.read_csv("UP_2022 (2).csv")

In [3]:
election_data

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank
0,1,Umar Ali Khan,Samajwadi Party,134513,47.81,1
1,1,Naresh Saini,Bharatiya Janata Party,96633,34.34,2
2,1,Rais Malik,Bahujan Samaj Party,45075,16.02,3
3,1,Poonam Kamboj,Indian National Congress,1632,0.58,4
4,1,Sushil Kumar,Aam Aadmi Party,1162,0.41,5
...,...,...,...,...,...,...
4840,403,HRIDAY KUMAR,Independent,1853,0.91,7
4841,403,ASHOK KUMAR,Jan Adhikar Party,1758,0.86,8
4842,403,MISHRI LAL,Independent,1317,0.64,9
4843,403,KRIPASHANKAR,All India Peoples' Front (Radical),894,0.44,10
4844,403,PUSHPA DEVI,Aam Aadmi Party,830,0.41,11

In [4]:
election_data.head()

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank
0,1,Umar Ali Khan,Samajwadi Party,134513,47.81,1
1,1,Naresh Saini,Bharatiya Janata Party,96633,34.34,2
2,1,Rais Malik,Bahujan Samaj Party,45075,16.02,3
3,1,Poonam Kamboj,Indian National Congress,1632,0.58,4
4,1,Sushil Kumar,Aam Aadmi Party,1162,0.41,5

In [5]:
election_data.tail()

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank
4840,403,HRIDAY KUMAR,Independent,1853,0.91,7
4841,403,ASHOK KUMAR,Jan Adhikar Party,1758,0.86,8
4842,403,MISHRI LAL,Independent,1317,0.64,9
4843,403,KRIPASHANKAR,All India Peoples' Front (Radical),894,0.44,10
4844,403,PUSHPA DEVI,Aam Aadmi Party,830,0.41,11

In [6]:
election_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ac_no        4845 non-null   int64
 1   Candidate    4845 non-null   object
 2   Party        4845 non-null   object
 3   Total Votes  4845 non-null   int64
 4   % of Votes   4845 non-null   float64
 5   Rank         4845 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 227.2+ KB

## Q1. How many constituencies did the Bharatiya Janata Party (BJP) win?

In [8]:
election_data[(election_data.Rank==1) & (election_data.Party=="Bharatiya Janata Party")]

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank
9,2,MUKESH CHOUDHARY,Bharatiya Janata Party,104114,38.47,1
21,3,RAJEEV GUMBER,Bharatiya Janata Party,143195,48.85,1
49,5,BRIJESH,Bharatiya Janata Party,93890,38.77,1
60,6,Devender Kumar Nim,Bharatiya Janata Party,89109,38.37,1
70,7,KIRAT SINGH,Bharatiya Janata Party,116582,43.08,1
...,...,...,...,...,...,...
4786,399,RAMA SHANKAR SINGH,Bharatiya Janata Party,105377,44.51,1
4801,400,Dr. Anil Kumar Maurya,Bharatiya Janata Party,101277,40.46,1
4814,401,Bhupesh Chaubey,Bharatiya Janata Party,84496,40.29,1
4825,402,SANJEEV KUMAR,Bharatiya Janata Party,78364,48.04,1
4834,403,RAMDULAR,Bharatiya Janata Party,84407,41.28,1

In [9]:
election_data[(election_data.Rank==1) & (election_data.Party=="Bharatiya Janata Party")]["ac_no"].count()

255

## Q2. Similarly calculate the number of constituencies won by each party.

In [11]:
election_data[election_data.Rank==1].groupby(["Party"])["ac_no"].count()

Party
Apna Dal (Soneylal)                      12
Bahujan Samaj Party                       1
Bharatiya Janata Party                  255
Indian National Congress                  2
Jansatta Dal Loktantrik                   2
Nirbal Indian Shoshit Hamara Aam Dal      6
Rashtriya Lok Dal                         8
Samajwadi Party                         111
Suheldev Bharatiya Samaj Party            6
Name: ac_no, dtype: int64

## Q3. In how many constituencies did the Bharatiya Janata Party and the Samajwadi Party occupy the first two ranks (i.e either BJP comes first and SP second or vice versa)

In [13]:
df_sorted = election_data.sort_values(['ac_no', 'Rank'], ascending=[True, True])

In [14]:
df_sorted

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank
0,1,Umar Ali Khan,Samajwadi Party,134513,47.81,1
1,1,Naresh Saini,Bharatiya Janata Party,96633,34.34,2
2,1,Rais Malik,Bahujan Samaj Party,45075,16.02,3
3,1,Poonam Kamboj,Indian National Congress,1632,0.58,4
4,1,Sushil Kumar,Aam Aadmi Party,1162,0.41,5
...,...,...,...,...,...,...
4840,403,HRIDAY KUMAR,Independent,1853,0.91,7
4841,403,ASHOK KUMAR,Jan Adhikar Party,1758,0.86,8
4842,403,MISHRI LAL,Independent,1317,0.64,9
4843,403,KRIPASHANKAR,All India Peoples' Front (Radical),894,0.44,10
4844,403,PUSHPA DEVI,Aam Aadmi Party,830,0.41,11

In [15]:
top_two = df_sorted.groupby("ac_no").head(2)

In [16]:
top_two_parties = top_two.groupby('ac_no')['Party'].apply(list)

In [17]:
count = top_two_parties.apply(lambda parties: set(parties) == {'Bharatiya Janata Party', 'Samajwadi Party'}).sum()

In [18]:
print(f"Number of constituencies where BJP and SP were top two: {count}")

Number of constituencies where BJP and SP were top two: 305

## Q4. In how many constituencies did the Bahujan Samaj Party come second.

In [20]:
election_data[(election_data.Rank==2) & (election_data.Party=="Bahujan Samaj Party")]['ac_no'].count()

18

In [21]:
district = pd.read_csv("UP_AC_District.csv")

In [22]:
district

     AC No.           AC Name    District
0         1             Behat  Saharanpur
1         2             Nakur  Saharanpur
2         3  Saharanpur Nagar  Saharanpur
3         4        Saharanpur  Saharanpur
4         5           Deoband  Saharanpur
..      ...               ...         ...
398     399           Marihan    Mirzapur
399     400          Ghorawal   Sonbhadra
400     401       Robertsganj   Sonbhadra
401     402              Obra   Sonbhadra
402     403            Duddhi   Sonbhadra

[403 rows x 3 columns]

## Q5. Find the number of constituencies in every district.

In [24]:
district.groupby(["District"])["AC No."].count()

District
Agra               9
Aligarh            7
Allahabad         12
Ambedkar Nagar     5
Auraiya            3
                  ..
Sitapur            9
Sonbhadra          4
Sultanpur          8
Unnao              6
Varanasi           8
Name: AC No., Length: 70, dtype: int64

## Q6. What were the top 3 districts for the Bharatiya Janata Party (evaluate on the basis of the % of seats won by the BJP in that district)

In [27]:
district.rename(columns={'AC No.':'ac_no'},inplace=True)

In [28]:
type(district)

pandas.core.frame.DataFrame

In [29]:
type(election_data)

pandas.core.frame.DataFrame

In [30]:
district.columns.tolist()

['ac_no', 'AC Name', 'District']

In [31]:
combined_election_data = pd.merge(election_data, district, on="ac_no" , how='inner')

In [32]:
combined_election_data

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank,AC Name,District
0,1,Umar Ali Khan,Samajwadi Party,134513,47.81,1,Behat,Saharanpur
1,1,Naresh Saini,Bharatiya Janata Party,96633,34.34,2,Behat,Saharanpur
2,1,Rais Malik,Bahujan Samaj Party,45075,16.02,3,Behat,Saharanpur
3,1,Poonam Kamboj,Indian National Congress,1632,0.58,4,Behat,Saharanpur
4,1,Sushil Kumar,Aam Aadmi Party,1162,0.41,5,Behat,Saharanpur
...,...,...,...,...,...,...,...,...
4840,403,HRIDAY KUMAR,Independent,1853,0.91,7,Duddhi,Sonbhadra
4841,403,ASHOK KUMAR,Jan Adhikar Party,1758,0.86,8,Duddhi,Sonbhadra
4842,403,MISHRI LAL,Independent,1317,0.64,9,Duddhi,Sonbhadra
4843,403,KRIPASHANKAR,All India Peoples' Front (Radical),894,0.44,10,Duddhi,Sonbhadra
4844,403,PUSHPA DEVI,Aam Aadmi Party,830,0.41,11,Duddhi,Sonbhadra

In [33]:
total_seats_per_district = combined_election_data.groupby('District')['AC Name'].nunique()

In [34]:
total_seats_per_district

District
Agra               9
Aligarh            7
Allahabad         12
Ambedkar Nagar     5
Auraiya            3
                  ..
Sitapur            9
Sonbhadra          4
Sultanpur          8
Unnao              6
Varanasi           8
Name: AC Name, Length: 70, dtype: int64

In [35]:
bjp_seats_per_district = combined_election_data[(combined_election_data.Party=="Bharatiya Janata Party") & (combined_election_data.Rank==1)].groupby(['District'])['ac_no'].count()

In [36]:
bjp_seats_per_district

District
Agra         9
Aligarh      7
Allahabad    7
Auraiya      1
Baghpat      2
            ..
Sitapur      8
Sonbhadra    4
Sultanpur    5
Unnao        6
Varanasi     7
Name: ac_no, Length: 65, dtype: int64

In [37]:
percentage_bjp_wins = (bjp_seats_per_district / total_seats_per_district * 100).dropna()

In [38]:
percentage_bjp_wins

District
Agra         100.000000
Aligarh      100.000000
Allahabad     58.333333
Auraiya       33.333333
Baghpat       66.666667
                ...
Sitapur       88.888889
Sonbhadra    100.000000
Sultanpur     62.500000
Unnao        100.000000
Varanasi      87.500000
Length: 65, dtype: float64

In [39]:
top_3_districts = percentage_bjp_wins.sort_values(ascending=False).head(3)

In [40]:
top_3_districts

District
Agra            100.0
Kanpur Dehat    100.0
Gonda           100.0
dtype: float64

## Q7. In how many constituencies, the difference in Total Votes between the Bharatiya Janata Party and the Samajwadi Party was less than 5000.

In [42]:
# Filter for BJP and SP only
filtered = combined_election_data[combined_election_data['Party'].isin(['Bharatiya Janata Party', 'Samajwadi Party'])]

In [43]:
filtered

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank,AC Name,District
0,1,Umar Ali Khan,Samajwadi Party,134513,47.81,1,Behat,Saharanpur
1,1,Naresh Saini,Bharatiya Janata Party,96633,34.34,2,Behat,Saharanpur
9,2,MUKESH CHOUDHARY,Bharatiya Janata Party,104114,38.47,1,Nakur,Saharanpur
10,2,DR. DHARAM SINGH SAINI,Samajwadi Party,103799,38.35,2,Nakur,Saharanpur
21,3,RAJEEV GUMBER,Bharatiya Janata Party,143195,48.85,1,Saharanpur Nagar,Saharanpur
...,...,...,...,...,...,...,...,...
4815,401,AVINASH KUSHWAHA,Samajwadi Party,78875,37.61,2,Robertsganj,Sonbhadra
4825,402,SANJEEV KUMAR,Bharatiya Janata Party,78364,48.04,1,Obra,Sonbhadra
4826,402,ARVIND KUMAR,Samajwadi Party,51922,31.83,2,Obra,Sonbhadra
4834,403,RAMDULAR,Bharatiya Janata Party,84407,41.28,1,Duddhi,Sonbhadra
4835,403,VIJAY SINGH,Samajwadi Party,78110,38.20,2,Duddhi,Sonbhadra

In [44]:
# Pivot table to get one row per constituency with BJP and SP votes as columns
pivot = filtered.pivot_table(index='ac_no', 
                             columns='Party', 
                             values='Total Votes', 
                             aggfunc='sum')

In [45]:
pivot

Party  Bharatiya Janata Party  Samajwadi Party
ac_no
1                     96633.0         134513.0
2                    104114.0         103799.0
3                    143195.0         135761.0
4                     76262.0         107007.0
5                     93890.0          86786.0
...                       ...              ...
399                  105377.0          42007.0
400                  101277.0          77355.0
401                   84496.0          78875.0
402                   78364.0          51922.0
403                   84407.0          78110.0

[400 rows x 2 columns]

In [46]:
# Drop rows where one of the parties didn't contest (i.e., has NaN)
pivot = pivot.dropna(subset=['Bharatiya Janata Party', 'Samajwadi Party'])

In [47]:
pivot

Party  Bharatiya Janata Party  Samajwadi Party
ac_no
1                     96633.0         134513.0
2                    104114.0         103799.0
3                    143195.0         135761.0
4                     76262.0         107007.0
5                     93890.0          86786.0
...                       ...              ...
399                  105377.0          42007.0
400                  101277.0          77355.0
401                   84496.0          78875.0
402                   78364.0          51922.0
403                   84407.0          78110.0

[323 rows x 2 columns]

In [48]:
# Calculate the vote difference
pivot['vote_diff'] = abs(pivot['Bharatiya Janata Party'] - pivot['Samajwadi Party'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_11248\1777945768.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pivot['vote_diff'] = abs(pivot['Bharatiya Janata Party'] - pivot['Samajwadi Party'])

In [49]:
pivot['vote_diff']

ac_no
1      37880.0
2        315.0
3       7434.0
4      30745.0
5       7104.0
        ...
399    63370.0
400    23922.0
401     5621.0
402    26442.0
403     6297.0
Name: vote_diff, Length: 323, dtype: float64

In [50]:
# Find constituencies with vote difference less than 5000
close_contests = pivot[pivot['vote_diff'] < 5000]

In [51]:
close_contests

Party  Bharatiya Janata Party  Samajwadi Party  vote_diff
ac_no
2                    104114.0         103799.0      315.0
20                    81791.0          81588.0      203.0
23                    90288.0          90522.0      234.0
28                   148384.0         147602.0      782.0
36                   101998.0         101691.0      307.0
46                   104924.0         107104.0     2180.0
96                   107453.0         108289.0      836.0
102                   87957.0          91958.0     4001.0
103                  102873.0          99063.0     3810.0
106                   91339.0          86898.0     4441.0
108                   97208.0          92441.0     4767.0
112                  108735.0         110569.0     1834.0
118                  120790.0         124145.0     3355.0
122                   92070.0          89149.0     2921.0
131                   77800.0          77443.0      357.0
132                   99609.0          95037.0     4572.0
144                   99377.0          94506.0     4871.0
146                   99349.0          98096.0     1253.0
181                   87715.0          85604.0     2111.0
182                   62359.0          66166.0     3807.0
187                   69360.0          69629.0      269.0
188                   92715.0          91706.0     1009.0
196                  124773.0         123662.0     1111.0
197                  106089.0         101481.0     4608.0
200                   98150.0          94166.0     3984.0
203                   80392.0          80865.0      473.0
250                   72934.0          75583.0     2649.0
256                  103557.0         100825.0     2732.0
259                   75116.0          78555.0     3439.0
266                  118720.0         118503.0      217.0
267                   98538.0          98799.0      261.0
269                  110576.0         113558.0     2982.0
286                  107628.0         103550.0     4078.0
290                   98640.0          97183.0     1457.0
305                   62591.0          64253.0     1662.0
306                   84327.0          85098.0      771.0
310                   84250.0          86029.0     1779.0
353                   79032.0          74584.0     4448.0
364                   82391.0          81065.0     1326.0
375                   90780.0          92472.0     1692.0
392                   95853.0         100738.0     4885.0
394                   93691.0          92044.0     1647.0

In [52]:
("Number of constituencies with vote difference < 5000:", len(close_contests))

('Number of constituencies with vote difference < 5000:', 42)

## Q8. For the consituencies in part 7, in how many constituencies did the BJP lose (did not come first)

In [54]:
# Get the list of those ac_no values
close_ac_nos = close_contests.index.tolist()

In [55]:
close_ac_nos

[2,
 20,
 23,
 28,
 36,
 46,
 96,
 102,
 103,
 106,
 108,
 112,
 118,
 122,
 131,
 132,
 144,
 146,
 181,
 182,
 187,
 188,
 196,
 197,
 200,
 203,
 250,
 256,
 259,
 266,
 267,
 269,
 286,
 290,
 305,
 306,
 310,
 353,
 364,
 375,
 392,
 394]

In [56]:
# From the original dataframe, get BJP candidates from those constituencies
bjp_in_close = combined_election_data[(combined_election_data['ac_no'].isin(close_ac_nos)) & (combined_election_data['Party'] == 'Bharatiya Janata Party')]

In [57]:
bjp_in_close

,ac_no,Candidate,Party,Total Votes,% of Votes,Rank,AC Name,District
9,2,MUKESH CHOUDHARY,Bharatiya Janata Party,104114,38.47,1,Nakur,Saharanpur
230,20,ASHOK KUMAR RANA,Bharatiya Janata Party,81791,39.89,1,Dhampur,Bijnor
265,23,KAMLESH SAINI,Bharatiya Janata Party,90288,40.24,2,Chandpur,Bijnor
327,28,RITESH KUMAR GUPTA,Bharatiya Janata Party,148384,46.12,1,Moradabad Nagar,Moradabad
417,36,Baldev Singh Aulakh,Bharatiya Janata Party,101998,43.17,1,Bilaspur,Rampur
525,46,SATYAVIR TYAGI,Bharatiya Janata Party,104924,41.33,2,Kithore,Meerut
1117,96,MANVENDRA PRATAP SINGH,Bharatiya Janata Party,107453,43.37,2,Jasrana,Firozabad
1186,102,Mamtesh Shakya,Bharatiya Janata Party,87957,40.06,2,Patiyali,Etah
1200,103,SATYAPAL SINGH RATHORE,Bharatiya Janata Party,102873,45.44,1,Aliganj,Etah
1243,106,SANJEEV KUMAR,Bharatiya Janata Party,91339,45.10,1,Jalesar,Etah
1263,108,Ram Naresh Agnihotri,Bharatiya Janata Party,97208,45.18,1,Bhongaon,Mainpuri
1295,112,KUSHAGRA SAGAR,Bharatiya Janata Party,108735,43.50,2,Bisauli,Budaun
1362,118,CHHATRA PAL SINGH,Bharatiya Janata Party,120790,45.41,2,Baheri,Bareilly
1400,122,PROF. SHYAM BIHARI LAL,Bharatiya Janata Party,92070,45.22,1,Faridpur,Bareilly
1514,131,Veer Vikram Singh,Bharatiya Janata Party,77800,39.90,1,Katra,Shahjahanpur
1526,132,Hari Prakash Verma,Bharatiya Janata Party,99609,45.97,1,Jalalabad,Shahjahanpur
1658,144,LOKENDRA PRATAP SINGH,Bharatiya Janata Party,99377,42.75,1,Mohammdi,Kheri
1682,146,Rakesh Rathour,Bharatiya Janata Party,99349,42.72,1,Sitapur,Sitapur
2100,181,ASHOK KUMAR,Bharatiya Janata Party,87715,43.79,1,Salon,Rae Bareli
2111,182,DHIRENDRA BAHADUR SINGH,Bharatiya Janata Party,62359,28.78,2,Sareni,Rae Bareli
2178,187,OM PRAKASH PANDEY,Bharatiya Janata Party,69360,34.21,2,Isauli,Sultanpur
2187,188,VINOD SINGH,Bharatiya Janata Party,92715,42.24,1,Sultanpur,Sultanpur
2272,196,Archana Pandey,Bharatiya Janata Party,124773,44.31,1,Chhibramau,Kannauj
2287,197,Kailash Rajput,Bharatiya Janata Party,106089,44.51,1,Tirwa,Kannauj
2316,200,Sarita,Bharatiya Janata Party,98150,39.97,1,Etawah,Etawah
2350,203,Lakhan Singh Rajput,Bharatiya Janata Party,80392,40.10,2,Dibiyapur,Auraiya
2907,250,ABHAY KUMAR ALIAS DHIRAJ OJHA,Bharatiya Janata Party,72934,38.65,2,Raniganj,Pratapgarh
3000,256,Praveen Patel,Bharatiya Janata Party,103557,42.00,1,Phulpur,Allahabad
3056,259,NEELAM KARVARIYA,Bharatiya Janata Party,75116,40.28,2,Meja,Allahabad
3146,266,Sakendra Pratap,Bharatiya Janata Party,118720,41.15,1,Kursi,Barabanki
3157,267,SHARAD KUMAR AWASTHI,Bharatiya Janata Party,98538,41.85,2,Ram Nagar,Barabanki
3177,269,Ambrish Rawat,Bharatiya Janata Party,110576,39.79,2,Zaidpur,Barabanki
3365,286,ANUPMA JAISWAL,Bharatiya Janata Party,107628,46.45,1,Bahraich,Bahraich
3411,290,Ram Feran,Bharatiya Janata Party,98640,38.98,1,Shrawasti,Shrawasti
3601,305,SATISH CHANDRA,Bharatiya Janata Party,62591,37.55,2,Itwa,Siddharthnagar
3611,306,RAGHVENDRA PRATAP SINGH,Bharatiya Janata Party,84327,40.82,2,Domariyaganj,Siddharthnagar
3663,310,Dayaram Chaudhary,Bharatiya Janata Party,84250,38.99,2,Basti Sadar,Basti
4213,353,RAM BILASH CHAUHAN,Bharatiya Janata Party,79032,35.24,1,Madhuban,Mau
4349,364,RAMESH CHANDRA MISHRA,Bharatiya Janata Party,82391,39.72,1,Badlapur,Jaunpur
4507,375,DR. SANGEETA BALWANT,Bharatiya Janata Party,90780,40.06,2,Ghazipur,Ghazipur
4706,392,RAVINDRA NATH TRIPATHI,Bharatiya Janata Party,95853,38.29,2,Bhadohi,S.R.Nagar(Bhadohi)
4728,394,Dinanath Bhashkar,Bharatiya Janata Party,93691,41.69,1,Aurai,S.R.Nagar(Bhadohi)

In [58]:
# Count how many of those BJP candidates did NOT have rank 1
bjp_losses = bjp_in_close[bjp_in_close['Rank'] != 1]

In [59]:
print("BJP lost in", len(bjp_losses), "constituencies out of those with <5000 vote difference.")

BJP lost in 18 constituencies out of those with <5000 vote difference.

## Q9. For every assembly constituency, find the number of parties that got more than 10,000 total votes.

In [126]:
combined_election_data[combined_election_data['Total Votes']>10000].groupby('AC Name')['ac_no'].count()

AC Name
Agra Cantt.        3
Agra North         3
Agra Rural         3
Agra South         3
Ajagara            3
                  ..
Vishwanath Ganj    5
Zafrabad           3
Zahoorabad         3
Zaidpur            4
Zamania            3
Name: ac_no, Length: 403, dtype: int64

## Q10. Calculate the district level vote % for each party. To calculate the vote % in a district. Add the total votes from all consituencies in that district for a party and divide it by the total votes in that district.

In [129]:
# Total votes for each party in each district
party_district_votes = combined_election_data.groupby(['District', 'Party'])['Total Votes'].sum().reset_index()

In [131]:
party_district_votes

      District                           Party  Total Votes
0         Agra                 Aam Aadmi Party         7802
1         Agra  Aazad Samaj Party (Kanshi Ram)         1119
2         Agra              Adarsh Samaj Party          260
3         Agra             Bahujan Mukti Party          149
4         Agra             Bahujan Samaj Party       473661
...        ...                             ...          ...
1469  Varanasi     Rashtriya Vikas Manch Party          378
1470  Varanasi           Right to Recall Party          149
1471  Varanasi                 Samajwadi Party       326216
1472  Varanasi           Sarvjan Sanatan Party          566
1473  Varanasi  Suheldev Bharatiya Samaj Party       179472

[1474 rows x 3 columns]

In [133]:
#  Total votes in each district (all parties)
district_total_votes = combined_election_data.groupby('District')['Total Votes'].sum().reset_index()
district_total_votes.rename(columns={'Total Votes': 'Total District Votes'}, inplace=True)

In [137]:
district_total_votes

          District  Total District Votes
0             Agra               2116833
1          Aligarh               1728326
2        Allahabad               2504317
3   Ambedkar Nagar               1148997
4          Auraiya                624541
..             ...                   ...
65         Sitapur               2090462
66       Sonbhadra                827674
67       Sultanpur               1654515
68           Unnao               1362301
69        Varanasi               1870943

[70 rows x 2 columns]

In [135]:
#  Merge total district votes into party-level data
merged = party_district_votes.merge(district_total_votes, on='District')

In [139]:
merged

,District,Party,Total Votes,Total District Votes
0,Agra,Aam Aadmi Party,7802,2116833
1,Agra,Aazad Samaj Party (Kanshi Ram),1119,2116833
2,Agra,Adarsh Samaj Party,260,2116833
3,Agra,Bahujan Mukti Party,149,2116833
4,Agra,Bahujan Samaj Party,473661,2116833
...,...,...,...,...
1469,Varanasi,Rashtriya Vikas Manch Party,378,1870943
1470,Varanasi,Right to Recall Party,149,1870943
1471,Varanasi,Samajwadi Party,326216,1870943
1472,Varanasi,Sarvjan Sanatan Party,566,1870943
1473,Varanasi,Suheldev Bharatiya Samaj Party,179472,1870943

In [141]:
# Calculate vote percentage
merged['District Vote %'] = (merged['Total Votes'] / merged['Total District Votes']) * 100
merged['District Vote %'] = merged['District Vote %'].round(2)

In [143]:
print(merged[['District', 'Party', 'District Vote %']])

      District                           Party  District Vote %
0         Agra                 Aam Aadmi Party             0.37
1         Agra  Aazad Samaj Party (Kanshi Ram)             0.05
2         Agra              Adarsh Samaj Party             0.01
3         Agra             Bahujan Mukti Party             0.01
4         Agra             Bahujan Samaj Party            22.38
...        ...                             ...              ...
1469  Varanasi     Rashtriya Vikas Manch Party             0.02
1470  Varanasi           Right to Recall Party             0.01
1471  Varanasi                 Samajwadi Party            17.44
1472  Varanasi           Sarvjan Sanatan Party             0.03
1473  Varanasi  Suheldev Bharatiya Samaj Party             9.59

[1474 rows x 3 columns]